VideoClub.WebMVC/Models/Provincia/ProvinciaEditVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VideoClub.WebMVC.Models.Provincias
{
    public class ProvinciaEditVm
    {
        public int ProvinciaId { get; set; }

        [DisplayName("Descripcion")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "el campo {0} debe tener entre {2} y {1} caracteres", MinimumLength = 2)]
        public string NombreProvincia { get; set; }
    }
}

VideoClub.WebMVC/Models/Provincia/ProvinciaListVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VideoClub.WebMVC.Models.Provincia
{
    public class ProvinciaListVm
    {
        public int ProvinciaId { get; set; }
        public string NombreProvincia { get; set; }
    }
}

VideoClub.WebMVC/Controllers/ProvinciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using VideoClub.Entidades.Entidades;
using VideoClub.Servicios.Servicios;
using VideoClub.Servicios.Servicios.Facades;
using VideoClub.WebMVC.App_Start;
using VideoClub.WebMVC.Models.Calificacion;
using VideoClub.WebMVC.Models.Provincia;
using VideoClub.WebMVC.Models.Provincias;

namespace VideoClub.WebMVC.Controllers
{
    public class ProvinciasController : Controller
    {
        // GET: Provincia
        private readonly IServicioProvincias servicio;
        private readonly IMapper mapper;

        public ProvinciasController(ServicioProvincias servicio)
        {
            this.servicio = servicio;
            mapper = AutoMapperConfig.Mapper;
        }

        public ActionResult Index()
        {
            var lista = servicio.GetLista();
            return View(lista);
        }

        [HttpGet]
        public JsonResult ListarProvincias()
        {
            var listaVm = mapper.Map<List<ProvinciaListVm>>(servicio.GetLista());

            return Json(new { data = listaVm }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetProvincia(int provinciaId)
        {
            var provinciaVm = mapper.Map<ProvinciaEditVm>(servicio.GetProvinciaPorId(provinciaId));
            return Json(provinciaVm, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Guardar(Provincia provincia)
        {
            bool respuesta = true;
            string mensaje = string.Empty;

            if (servicio.Existe(provincia))
            {
                respuesta = false;
                mensaje = "Provincia Repetida!";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }

            try
            {
                servicio.Guardar(provincia);
                respuesta = true;
                mensaje = "Registro guardado";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                respuesta = false;
                mensaje = "Error al intentar guardar el registro";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public JsonResult Eliminar(int provinciaId)
        {
            var respuesta = true;
            var mensaje = string.Empty;
            try
            {
                var provincia = servicio.GetProvinciaPorId(provinciaId);
                if (servicio.EstaRelacionado(provincia))
                {
                    respuesta = false;
                    mensaje = "Provincia relacionada... \nNo se pudo eliminar la provincia";
                    return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
                }
                servicio.Borrar(provincia.ProvinciaId);
                respuesta = true;
                mensaje = "Provincia eliminada!";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                respuesta = false;
                mensaje = "Error al intentar eliminar la provincia";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

VideoClub.WebMVC/Views/Provincias/Index.cshtml
@{ ViewBag.Title = "Index"; }

<script src="~/Scripts/jquery-3.7.1.min.js"></script>
<script src="~/Scripts/toastr.js"></script>
<div class="card">

    <h5 class="card-header bg-dark text-white">
        <i class="fas fa-map"></i>
        Listado de Provincias

    </h5>
    <div class="card-body">
        <button id="btnNuevo" onclick="abrirModal(0)" class="btn btn-primary"><i class="fa fa-plus"></i> Nuevo </button>
        <hr/>
        <table id="tablaProvincias" class="table display cell-border">
            <thead>
            <tr>
                <th>Provincias</th>
                <th></th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalProvincia" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Datos de la Provincia</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="ProvinciaId" />
                    <div class="mb-3">
                        <label for="NombreProvincia" class="col-form-label">Provincia:</label>
                        <input type="text" class="form-control" id="NombreProvincia">
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" onclick="Guardar()" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        var tablaProvincias;
        $(document).ready(function() {
            tablaProvincias = $('#tablaProvincias').DataTable({
                "ajax": {
                    "url": "@Url.Action("ListarProvincias", "Provincias")",
                    type: "GET",
                    dataType: "json"
                },
                "columns": [
                    { "data": "NombreProvincia" },
                    {
                        "data": "ProvinciaId",
                        "render": function(data) {
                            return "<button class='btn btn-warning btn-sm' type='button' onclick='abrirModal(" +
                                data +
                                ")'><i class='fas fa-pen'></i></button> " +
                                "<button class='btn btn-danger btn-sm' type='button' onclick='" +
                                "Eliminar(" +
                                data +
                                ")'><i class='fas fa-trash'></i></button> ";
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "100px"
                    }
                ]

            });
        });


        function abrirModal($provinciaId) {
            $("#ProvinciaId").val($provinciaId);
            if ($provinciaId != 0) {
                $.ajax({
                    "url": "@Url.Action("GetProvincia", "Provincias")" + "?provinciaId=" + $provinciaId,
                    "type": "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function(data) {
                        console.log(data);
                        if (data != null) {
                            $("#NombreProvincia").val(data.NombreProvincia);

                        }

                    }
                });
            } else {
                $("#NombreProvincia").val("");

            }
            $("#modalProvincia").modal('show');
        }

        function Guardar() {
            var $data = {
                provincia: {
                    "ProvinciaId": $("#ProvinciaId").val(),
                    "NombreProvincia": $("#NombreProvincia").val()

                }

            }
            console.log($data);
            $.ajax({
                "url": "@Url.Action("Guardar", "Provincias")",
                "type": "POST",
                "data": JSON.stringify($data),
                "contentType": "application/json, charset=utf-8",
                success: function(response) {
                    if (response.resultado) {
                        $("#modalProvincia").modal('hide');
                        toastr.success(response.mensaje);
                        tablaProvincias.ajax.reload();

                    } else {
                        toastr.error(response.mensaje);

                    }
                },
                error: function(response) {
                    toastr.error(response.mensaje);
                }
            });
        }

        function Eliminar($ProvinciaId) {
            if (confirm("Desea eliminar el registro seleccionado?")) {
                $.ajax({
                    "url": "@Url.Action("Eliminar", "Provincias")" + "?provinciaId=" + $ProvinciaId,
                    "type": "POST",
                    contentType: "application/json; charset=utf-8",
                    success: function(response) {
                        if (response.resultado) {
                            toastr.success(response.mensaje);
                            tablaProvincias.ajax.reload();
                        } else {
                            toastr.error(response.mensaje);
                        }
                    },
                    error: function(response) {
                        toastr.error(response.mensaje);
                    }
                });

            };
        }

    </script>
}