VideoClub.WebMVC/Models/Calificacion/CalificacionEditVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VideoClub.WebMVC.Models.Calificacion
{
    public class CalificacionEditVm
    {
        public int CalificacionId { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "el campo {0} debe tener entre {2} y {1} caracteres",MinimumLength=2)]
        public string Descripcion { get; set; }
    }
}

VideoClub.WebMVC/Controllers/CalificacionController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoClub.Entidades.Entidades;
using VideoClub.Servicios.Servicios;
using VideoClub.Servicios.Servicios.Facades;
using VideoClub.WebMVC.App_Start;
using VideoClub.WebMVC.Models.Calificacion;

namespace VideoClub.WebMVC.Controllers
{
    public class CalificacionController : Controller
    {
        // GET: Calificacion
        private readonly IServicioCalificaciones servicio;
        private readonly IMapper mapper;
        public CalificacionController(ServicioCalificaciones servicio)
        {
            this.servicio = servicio;
            mapper = AutoMapperConfig.Mapper;
        }

        [HttpGet]
        public JsonResult ListarCalificaciones()
        {
            var lista = servicio.GetLista();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Index()
        {
            var lista = servicio.GetLista();
            return View(lista);
        }
 
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CalificacionEditVm calificacionEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(calificacionEditVm);
            }
            try
            {
                Calificacion calificacion = mapper.Map<Calificacion>(calificacionEditVm);
                if (servicio.Existe(calificacion))
                {
                    ModelState.AddModelError(string.Empty, "Calificacion existente!!!");
                    return View(calificacionEditVm);
                }
                servicio.Guardar(calificacion);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(calificacionEditVm);
            }
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Calificacion calificacion = servicio.GetCalificacionPorId(id.Value);
            if (calificacion == null)
            {
                return HttpNotFound("El codigo de la Calificacion no existe!");
            }

            CalificacionEditVm calificacionEditVm = mapper.Map<CalificacionEditVm>(calificacion);
            return View(calificacionEditVm);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CalificacionEditVm calificacionEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(calificacionEditVm);
            }

            Calificacion calificacion = mapper.Map<Calificacion>(calificacionEditVm);
            try
            {
                if (servicio.Existe(calificacion))
                {
                    ModelState.AddModelError(string.Empty, "Calificacion existente!");
                    return View(calificacionEditVm);
                }
                servicio.Guardar(calificacion);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(calificacionEditVm);
            }
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Calificacion calificacion = servicio.GetCalificacionPorId(id.Value);
            if (calificacion == null)
            {
                return HttpNotFound("El codigo de la calificacion no existe!");
            }

            CalificacionEditVm calificacionEditVm = mapper.Map<CalificacionEditVm>(calificacion);
            return View(calificacionEditVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Calificacion calificacion = servicio.GetCalificacionPorId(id);
            try
            {
                if (servicio.EstaRelacionado(calificacion))
                {
                    CalificacionEditVm calificacionEditVm = mapper.Map<CalificacionEditVm>(calificacion);
                    ModelState.AddModelError(string.Empty, "Calificacion relacionada!");
                    return View(calificacionEditVm);
                }

                servicio.Borrar(calificacion);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                CalificacionEditVm calificacionEditVm = mapper.Map<CalificacionEditVm>(calificacion);
                ModelState.AddModelError(string.Empty, e.Message);
                return View(calificacionEditVm);
            }
        }
    }
}

VideoClub.WebMVC/Views/Calificacion/Create.cshtml
@model VideoClub.WebMVC.Models.Calificacion.CalificacionEditVm

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h5 class="mt-3">Nueva Calificacion</h5>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-dark" })
            </div>
        </div>
    </div>}

VideoClub.WebMVC/Views/Calificacion/Delete.cshtml
@model VideoClub.WebMVC.Models.Calificacion.CalificacionEditVm

@{ ViewBag.Title = "Delete";
                Layout = "~/Views/Shared/_Layout.cshtml"; }
<hr />
<h4>Eliminar Calificacion</h4>
<hr />
<h5>Está seguro de borrar el registro?</h5>
<hr />
<div>
    <dl class="dl-horizontal">

        <dt>@Html.DisplayNameFor(model => model.Descripcion): </dt> 

        <dd>@Html.DisplayFor(model => model.Descripcion)</dd>

    </dl>

    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Borrar" class="btn btn-danger" />
                    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
                </div>}
</div>
<hr />

VideoClub.WebMVC/Views/Calificacion/Edit.cshtml
@model VideoClub.WebMVC.Models.Calificacion.CalificacionEditVm

@{ ViewBag.Title = "Edit";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<h5 class="mt-3">Editar Calificacion</h5>
<hr />

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.CalificacionId);

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Editar" class="btn btn-warning" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
        </div>
    </div>
</div>}

<div>
</div>

VideoClub.WebMVC/Views/Calificacion/Index.cshtml
@model List<VideoClub.Entidades.Entidades.Calificacion>
@{ ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="card">
    <h5 class="card-header bg-dark text-white">
        <i class="fas fa-star"></i>
        Listado de Calificaciones

    </h5>
    <div class="card-body">
        <a href="@Url.Action("Create","Calificacion")" class="btn btn-primary"><i class="fas fa-plus"></i> Nuevo</a>
        <hr />
        <table class="table">
            <thead>
                <tr>
                    <th>Calificacion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr>
                        <td>
                            No hay registros todavía
                        </td>
                    </tr>
 }
                else
                {
                    foreach (var calificacion in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => calificacion.Descripcion)</td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id = calificacion.CalificacionId }, new { @class = "btn btn-warning" })
                                @Html.ActionLink("Borrar", "Delete", new { id = calificacion.CalificacionId }, new { @class = "btn btn-danger" })

                            </td>
                        </tr>

                    }
                }
            </tbody>
        </table>

    </div>
    <div class="card-footer text-muted">
        Cantidad de registros: <strong>@Model.Count</strong>
    </div>
</div>