VideoClub.WebMVC/Controllers/EstadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using VideoClub.Entidades.Entidades;
using VideoClub.Servicios.Servicios;
using VideoClub.Servicios.Servicios.Facades;
using VideoClub.WebMVC.App_Start;
using VideoClub.WebMVC.Models.Calificacion;
using VideoClub.WebMVC.Models.Estado;

namespace VideoClub.WebMVC.Controllers
{
    public class EstadoController : Controller
    {
        // GET: Estado

        private readonly IServicioEstados servicio;
        private readonly IMapper mapper;
        public EstadoController(ServicioEstados servicio)
        {
            this.servicio = servicio;
            mapper = AutoMapperConfig.Mapper;
        }

        [HttpGet]
        public JsonResult ListarEstados()
        {
            var lista = servicio.GetLista();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Index()
        {
            var lista = servicio.GetLista();
            return View(lista);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EstadoEditVm estadoEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(estadoEditVm);
            }
            try
            {
                Estado estado = mapper.Map<Estado>(estadoEditVm);
                if (servicio.Existe(estado))
                {
                    ModelState.AddModelError(string.Empty, "Estado existente!!!");
                    return View(estadoEditVm);
                }
                servicio.Guardar(estado);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(estadoEditVm);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Estado estado = servicio.GetEstadoPorId(id.Value);
            if (estado == null)
            {
                return HttpNotFound("El codigo del estado no existe!");
            }

            EstadoEditVm estadoEditVm = mapper.Map<EstadoEditVm>(estado);
            return View(estadoEditVm);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EstadoEditVm estadoEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(estadoEditVm);
            }

            Estado estado = mapper.Map<Estado>(estadoEditVm);
            try
            {
                if (servicio.Existe(estado))
                {
                    ModelState.AddModelError(string.Empty, "Estado existente!");
                    return View(estadoEditVm);
                }
                servicio.Guardar(estado);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(estadoEditVm);
            }
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Estado estado = servicio.GetEstadoPorId(id.Value);
            if (estado == null)
            {
                return HttpNotFound("El codigo del estado no existe!");
            }

            EstadoEditVm estadoEditVm = mapper.Map<EstadoEditVm>(estado);
            return View(estadoEditVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Estado estado = servicio.GetEstadoPorId(id);
            try
            {
                if (servicio.EstaRelacionado(estado))
                {
                    EstadoEditVm estadoEditVm = mapper.Map<EstadoEditVm>(estado);
                    ModelState.AddModelError(string.Empty, "Estado relacionado!");
                    return View(estadoEditVm);
                }

                servicio.Borrar(estado);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                EstadoEditVm estadoEditVm = mapper.Map<EstadoEditVm>(estado);
                ModelState.AddModelError(string.Empty, e.Message);
                return View(estadoEditVm);
            }
        }
    }
}

VideoClub.WebMVC/Controllers/GeneroController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoClub.Entidades.Entidades;
using VideoClub.Servicios.Servicios;
using VideoClub.Servicios.Servicios.Facades;
using VideoClub.WebMVC.App_Start;
using VideoClub.WebMVC.Models.Genero;

namespace VideoClub.WebMVC.Controllers
{
    public class GeneroController : Controller
    {
        // GET: Genero
        private readonly IServicioGeneros servicio;
        private readonly IMapper mapper;
        public GeneroController(ServicioGeneros servicio)
        {
            this.servicio = servicio;
            mapper = AutoMapperConfig.Mapper;
        }

        [HttpGet]
        public JsonResult ListarGeneros()
        {
            var lista = servicio.GetLista();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Index()
        {
            var lista = servicio.GetLista();
            return View(lista);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GeneroEditVm generoEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(generoEditVm);
            }
            try
            {
                Genero genero = mapper.Map<Genero>(generoEditVm);
                if (servicio.Existe(genero))
                {
                    ModelState.AddModelError(string.Empty, "Genero existente!!!");
                    return View(generoEditVm);
                }
                servicio.Guardar(genero);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(generoEditVm);
            }
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Genero genero = servicio.GetGeneroPorId(id.Value);
            if (genero == null)
            {
                return HttpNotFound("El codigo del Genero no existe!");
            }

            GeneroEditVm generoEditVm = mapper.Map<GeneroEditVm>(genero);
            return View(generoEditVm);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GeneroEditVm generoEditVm)
        {
            if (!ModelState.IsValid)
            {
                return View(generoEditVm);
            }

            Genero genero = mapper.Map<Genero>(generoEditVm);
            try
            {
                if (servicio.Existe(genero))
                {
                    ModelState.AddModelError(string.Empty, "Genero existente!");
                    return View(generoEditVm);
                }
                servicio.Guardar(genero);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(generoEditVm);
            }
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            Genero genero = servicio.GetGeneroPorId(id.Value);
            if (genero == null)
            {
                return HttpNotFound("El codigo del genero no existe!");
            }

            GeneroEditVm calificacionEditVm = mapper.Map<GeneroEditVm>(genero);
            return View(calificacionEditVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Genero genero = servicio.GetGeneroPorId(id);
            try
            {
                if (servicio.EstaRelacionado(genero))
                {
                    GeneroEditVm generoEditVm = mapper.Map<GeneroEditVm>(genero);
                    ModelState.AddModelError(string.Empty, "Genero relacionado!");
                    return View(generoEditVm);
                }

                servicio.Borrar(genero);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                GeneroEditVm generoEditVm = mapper.Map<GeneroEditVm>(genero);
                ModelState.AddModelError(string.Empty, e.Message);
                return View(generoEditVm);
            }
        }
    }
}

VideoClub.WebMVC/Controllers/SocioController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using VideoClub.Entidades.Entidades;
using VideoClub.Servicios.Servicios.Facades;
using VideoClub.WebMVC.App_Start;
using VideoClub.WebMVC.Models.Localidad;
using VideoClub.WebMVC.Models.Provincia;
using VideoClub.WebMVC.Models.Socio;

namespace VideoClub.WebMVC.Controllers
{
    public class SocioController : Controller
    {
        private readonly IServicioSocios servicio;
        private readonly IServicioTiposDeDocumentos servicioTipoDoc;
        private readonly IServicioLocalidades servicioLocalidades;
        private readonly IServicioProvincias servicioProvincias;
        private readonly IMapper mapper;

        public SocioController(IServicioSocios servicio, IServicioTiposDeDocumentos servicioTipoDoc, IServicioLocalidades serIservicioLocalidades, IServicioProvincias servicioProvincias)
        {
            this.servicio = servicio;
            this.servicioTipoDoc = servicioTipoDoc;
            this.servicioLocalidades = serIservicioLocalidades;
            this.servicioProvincias = servicioProvincias;
            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Socio
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarSocios()
        {
            var listaSociosVm = mapper.Map<List<SocioListVm>>(servicio.GetLista());
            return Json(new { data = listaSociosVm }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ListarSocio(int socioId)
        {
            var socioVm = mapper.Map<SocioEditVm>(servicio.GetSocioPorId(socioId));
            return Json(socioVm, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult ListarProvincias()
        {
            var listaProvinciasVm = mapper.Map<List<ProvinciaListVm>>(servicioProvincias.GetLista());
            return Json(new { data = listaProvinciasVm }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarLocalidades(int provinciaId)
        {
            var listaLocalidadesVm = mapper.Map<List<LocalidadListVm>>(servicioLocalidades.GetLista(provinciaId));
            return Json(new { data = listaLocalidadesVm }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarSocio(string objeto)
        {
            bool respuesta = true;
            string mensaje = string.Empty;

            Socio socio = new Socio();
            socio = JsonConvert.DeserializeObject<Socio>(objeto);

            mensaje = ValidarSocio(socio);
            if (mensaje != string.Empty)
            {
                respuesta = false;
                return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }
            try
            {
                if (servicio.Existe(socio))
                {
                    respuesta = false;
                    mensaje = "Socio existente!";
                    return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
                }
                servicio.Guardar(socio);
                respuesta = true;
                mensaje = "Registro guardado";
                return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                respuesta = false;
                mensaje = "Error al intentar guardar el registro";
                return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

            }
        }
        private string ValidarSocio(Socio socio)
        {
            StringBuilder sb = new StringBuilder();
            if (string.IsNullOrEmpty(socio.Nombre))
            {
                sb.AppendLine("Nombre del socio es requerido");
            }
            if (string.IsNullOrEmpty(socio.Apellido))
            {
                sb.AppendLine("Apellido del socio es requerido");
            }
            if (socio.TipoDeDocumentoId == 0)
            {
                sb.AppendLine("Debe seleccionar una tipo de documento");
            }
            if ((socio.NroDocumento == null))
            {
                sb.AppendLine("Numero de Documento del socio es requerido");
            }
            if (string.IsNullOrEmpty(socio.Direccion))
            {
                sb.AppendLine("La direccion es requerida");
            }
            if (socio.ProvinciaId == 0)
            {
                sb.AppendLine("Debe seleccionar una provincia");
            }
            if (socio.LocalidadId == 0)
            {
                sb.AppendLine("Debe seleccionar una localidad");
            }
           


            return sb.ToString();
        }
        [HttpPost]
        public JsonResult EliminarSocio(int socioId)
        {
            var respuesta = true;
            var mensaje = string.Empty;
            try
            {
                var socio = servicio.GetSocioPorId(socioId);
                if (servicio.EstaRelacionado(socio))
                {
                    respuesta = false;
                    mensaje = "Socio relacionado... \nNo se pudo eliminar el socio";
                    return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
                }
                servicio.Borrar(socio.SocioId);
                respuesta = true;
                mensaje = "Socio eliminado!";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                respuesta = false;
                mensaje = "Error al intentar eliminar el socio";
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }

        }

    }
}

VideoClub.WebMVC/Controllers/TipoDeDocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using VideoClub.Entidades.Entidades;
using VideoClub.Servicios.Servicios;
using VideoClub.Servicios.Servicios.Facades;
using VideoClub.WebMVC.App_Start;
using VideoClub.WebMVC.Models.Provincias;
using VideoClub.WebMVC.Models.Tipo_de_Documento;

namespace VideoClub.WebMVC.Controllers
{
    public class TipoDeDocumentoController : Controller
    {
        // GET: TipoDeDocumento
        private readonly IServicioTiposDeDocumentos servicio;
        private readonly IMapper mapper;
        public TipoDeDocumentoController(ServicioTiposDeDocumentos servicio)
        {
            this.servicio = servicio;
            mapper = AutoMapperConfig.Mapper;
        }

        [HttpGet]
        public JsonResult ListarTiposDeDocumentos()
        {
            var lista = servicio.GetLista();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Index()
        {
            var lista = servicio.GetLista();
            return View(lista);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
       

    }
}

VideoClub.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VIDEO CLUB VIRTUAL</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html"><div class="sb-nav-link-icon"><i class="fas fa-film "></i> THE FILM ZONE</div></a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>

    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Ubicaciones</div>

                        <a class="nav-link" href="@Url.Action("Index","Provincias")">
                            <div class="sb-nav-link-icon"><i class="fas fa-map "></i></div>
                            Provincias
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Localidad")">
                            <div class="sb-nav-link-icon"><i class="fas fa-map-marker-alt "></i></div>
                            Localidades
                        </a>

                        <div class="sb-sidenav-menu-heading">Peliculas</div>
                        <a class="nav-link" href="@Url.Action("Index","Soporte")">
                            <div class="sb-nav-link-icon"><i class="fas fa-compact-disc"></i></div>
                            Soportes
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Calificacion")">
                            <div class="sb-nav-link-icon"><i class="fas fa-star"></i></div>
                            Calificaciones
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Genero")">
                            <div class="sb-nav-link-icon"><i class="fas fa-theater-masks"></i></div>
                            Generos
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Estado")">
                            <div class="sb-nav-link-icon"><i class="fas fa-check-circle"></i></div>
                            Estados
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Pelicula")">
                            <div class="sb-nav-link-icon"><i class="fas fa-film"></i></div>
                            Peliculas
                        </a>

                        <div class="sb-sidenav-menu-heading">Personas</div>

                        <a class="nav-link" href="@Url.Action("Index","Socio")">
                            <div class="sb-nav-link-icon"><i class="fas fa-handshake"></i></div>
                            Socios
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Empleado")">
                            <div class="sb-nav-link-icon"><i class="fas fa-people-carry"></i></div>
                            Empleados
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Proveedor")">
                            <div class="sb-nav-link-icon"><i class="fab fa-product-hunt"></i></div>
                            Proveedores
                        </a>
                        <div class="sb-sidenav-menu-heading">Otro</div>
                        <a class="nav-link" href="@Url.Action("Index","TipoDeDocumento")">
                            <div class="sb-nav-link-icon"><i class="fas fa-address-card"></i></div>
                            Tipos de Documentos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Diseñado por :</div>
                    Matias Cuello
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body> 
</html>